spring.application.name=TCPService

# ???
spring.datasource.url=jdbc:mysql://localhost:3306/light
spring.datasource.username=root
spring.datasource.password=DOOM1Sf0r3v3r
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ????
mybatis.configuration.map-underscore-to-camel-case=true

# ???,????????????????
server.port=18081

# debug=true

#* Spring AI 相关配置

#! 警告: 请不要移除这个配置. Spring AI的自动装配强制要求`spring.ai.openai.api-key`, 因此我们准备了[[AIAutowiredConfig]]来处理模拟AI回复.
#! 一旦移除这个配置, 程序将无法正常启动.
spring.autoconfigure.exclude=org.springframework.ai.autoconfigure.openai.OpenAiAutoConfiguration

spring.ai.openai.api-key=
spring.ai.openai.base-url=https://chat.deepseek.com/
spring.ai.openai.chat.options.model=deepseek-chat
spring.ai.openai.chat.options.temperature=0.7